# Generated by Django 2.1.4 on 2019-01-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Contributors', models.CharField(blank=True, max_length=50)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Teaser', models.CharField(max_length=140)),
                ('Videolink', models.CharField(max_length=500)),
                ('lon', models.DecimalField(decimal_places=6, default=9.6554, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=6, default=52.3194, max_digits=8)),
                ('Upload_Time', models.DateTimeField(auto_now_add=True)),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lokalreport.Channel')),
            ],
        ),
    ]
